version: '3'

services:
  incident-response:
    build: .
    container_name: soar-lite-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./:/app
      - ./data:/app/data
      - ./output:/app/output
      - ./logs:/app/logs
      - ./models:/app/models
    restart: unless-stopped