import json


def generate_html_report(json_path):
    """
    Generates an HTML report with enriched alerts.
    """
    with open(json_path, 'r') as f:
        results = json.load(f)

    html = """
    <html>
    <head>
        <title>SOAR-Lite Threat Intel Automation - Report</title>
        <style>
            body { font-family: Arial, sans-serif; margin: 40px; }
            table { border-collapse: collapse; width: 100%; }
            th, td { border: 1px solid #ccc; padding: 8px; text-align: left; }
            th { background-color: #f4f4f4; }
            h1 { color: #333; }
            footer { margin-top: 40px; font-size: 0.9em; color: #666; }
        </style>
    </head>
    <body>
        <h1>SOAR-Lite Threat Intel Automation – Enriched Alert Report</h1>
        <table>
            <tr>
                <th>Timestamp</th>
                <th>IP</th>
                <th>Event</th>
                <th>Risk</th>
                <th>Action</th>
                <th>Country</th>
            </tr>
    """

    for item in results:
        html += f"""
        <tr>
            <td>{item['timestamp']}</td>
            <td>{item['src_ip']}</td>
            <td>{item['event_type']}</td>
            <td>{item['risk_score']}</td>
            <td>{item['suggested_action']}</td>
            <td>{item['enrichment'].get('country', 'N/A')}</td>
        </tr>
        """

    html += """
        </table>
        <footer>
            <p>Generated by <strong>SOAR-Lite Threat Intel Automation</strong><br>
            Author: Renato Kopke © 2025</p>
        </footer>
    </body>
    </html>
    """

    return html